/// Flutter icons SOEIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SOEIcons
///      fonts:
///       - asset: fonts/SOEIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SOEIcons {
  SOEIcons._();

  static const _kFontFam = 'SOEIcons';
  static const String? _kFontPkg = null;

  static const IconData gamepad = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_vector = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData movie = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData practice = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData retry = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_vector = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData school = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sidebar = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speak = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_group = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dialogue = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
